In [4]:
import numpy as np

In [5]:
x=[1,2,3,4]

In [6]:
nx = np.array(x)

In [7]:
y = np.array([1,2,3,4,5])

In [8]:
print(y.ndim)      #dimensions
print(y.shape)     #shape of array
print(y.size)      #element count

1
(5,)
5


In [28]:
z = np.array([[1,2,3],[5,6,7],[9,10,11]])
print(y.ndim)      #dimensions
print(y.shape)     #shape of array
print(y.size)      #element count

1
(252,)
252


In [10]:
a = np.arange(10,100,.1)
print(a.size)
a2 = a.reshape((30,30))
print(a2.shape)

a3 = a.reshape((30,15,2))
print(a3)

900
(30, 30)
[[[10.  10.1]
  [10.2 10.3]
  [10.4 10.5]
  [10.6 10.7]
  [10.8 10.9]
  [11.  11.1]
  [11.2 11.3]
  [11.4 11.5]
  [11.6 11.7]
  [11.8 11.9]
  [12.  12.1]
  [12.2 12.3]
  [12.4 12.5]
  [12.6 12.7]
  [12.8 12.9]]

 [[13.  13.1]
  [13.2 13.3]
  [13.4 13.5]
  [13.6 13.7]
  [13.8 13.9]
  [14.  14.1]
  [14.2 14.3]
  [14.4 14.5]
  [14.6 14.7]
  [14.8 14.9]
  [15.  15.1]
  [15.2 15.3]
  [15.4 15.5]
  [15.6 15.7]
  [15.8 15.9]]

 [[16.  16.1]
  [16.2 16.3]
  [16.4 16.5]
  [16.6 16.7]
  [16.8 16.9]
  [17.  17.1]
  [17.2 17.3]
  [17.4 17.5]
  [17.6 17.7]
  [17.8 17.9]
  [18.  18.1]
  [18.2 18.3]
  [18.4 18.5]
  [18.6 18.7]
  [18.8 18.9]]

 [[19.  19.1]
  [19.2 19.3]
  [19.4 19.5]
  [19.6 19.7]
  [19.8 19.9]
  [20.  20.1]
  [20.2 20.3]
  [20.4 20.5]
  [20.6 20.7]
  [20.8 20.9]
  [21.  21.1]
  [21.2 21.3]
  [21.4 21.5]
  [21.6 21.7]
  [21.8 21.9]]

 [[22.  22.1]
  [22.2 22.3]
  [22.4 22.5]
  [22.6 22.7]
  [22.8 22.9]
  [23.  23.1]
  [23.2 23.3]
  [23.4 23.5]
  [23.6 23.7]
  [23.8 23.9]

In [11]:
b = np.linspace(1,10,100)
print(b)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [12]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)
print(a+b)
print(a.max())
print(a.mean())
print(a.min())
print(a.std())
print(a.sum())
print(a.max(axis=0))
print(a.max(axis=1))

[[1 2 5]
 [6 6 8]
 [6 7 2]]
[[8 8 4]
 [2 1 7]
 [1 1 3]]
[[ 9 10  9]
 [ 8  7 15]
 [ 7  8  5]]
8
4.777777777777778
1
2.3465235646603197
43
[6 7 8]
[5 8 7]


In [ ]:
t = np.arange(-np.pi*3, np.pi,.05)
x = np.sin(t)
y = np.cos(t)
import matplotlib.pyplot as plt
plt.plot(t,x,'r--o')
plt.plot(t,y,'g:x')
plt.title('visualization')
plt.show()

In [25]:
import numpy as np
x = np.random.randint(1,100,(6,6))
print(x)

[[43 20 54 28  3 82]
 [11 38 77 51 88 46]
 [28 96  1 70 38 40]
 [45 19 47 34 97 93]
 [25 80 25 41 13 59]
 [96 32 82 27 48 91]]


In [26]:
x[0,1]

20

In [27]:
x[:,0]

array([43, 11, 28, 45, 25, 96])

In [30]:
a = np.array([[1,2,3,4],[6,4,2,2],[2,3,4,3],[1,2,4,1]])
print(a)



[[1 2 3 4]
 [6 4 2 2]
 [2 3 4 3]
 [1 2 4 1]]


In [32]:
print(a[1:,0:3])

[[6 4 2]
 [2 3 4]
 [1 2 4]]
